### ISSUE TITLE
"No schema supplied" error for python 2.7.6 requests

### ISSUE THREAD

**Issue by acriptis** [SatoshiReport/1Broker#2]
@SatoshiReport Thank you for your script, just imported it into my system. 

But when I explored it, just after I've launched broker1_example_v2.py I've got error:
```
***** User Details
Invalid URL '1broker.com/api/v2/user/details.php': No schema supplied. Perhaps you meant http://1broker.com/api/v2/user/details.php?
```

I've fixed it in the line:
https://github.com/SatoshiReport/1Broker/blob/master/broker1_api_v2.py#L8

by substituting it from
```url = "1broker.com"```
to
```url = "https://1broker.com"```

May be it would be fine to fix it in your master code.

**Comment by SatoshiReport** [comment]
Resolved.  Thank you for pointing this out.
